### ISSUE TITLE
Evenly space buttons on the header

### ISSUE THREAD

**Issue by jacebrowning** [friendlycode/homepage#15]
Let's see if we can't get rid of this extra black space:

<img width="663" alt="screen shot 2015-10-06 at 6 33 57 pm" src="https://cloud.githubusercontent.com/assets/939501/10324594/d3d244be-6c58-11e5-9c8e-6426b30e9a9a.png">

**Comment by joel6653** [comment]
It occurred to me since our meeting last night that we should take the "social media" links, turn them into icons-only (the way you see it on many other web sites), and right-justify them (and them alone) in the black menu-bar.  And then combine "Contact" and "Connect."  This would make the menu-bar look much more balanced, plus it would make the links to our social media presence much more visible at the top level, without taking up a lot of space or using a lot of words.  Let me know what you think.

**Comment by jacebrowning** [comment]
Sound good to me!

**Comment by Crevax** [comment]
I'd suggest using Font Awsome for that. http://fontawesome.io/icons/#brand
